
		align	4
		label	L827_len__hla_ word
		dd	01dh
		dd	01dh
		label	L827_str__hla_ byte
		db	"sumIsPositive returned false!"
		db	0

		db	0
		db	0

		align	4
		label	L846_len__hla_ word
		dd	01ch
		dd	01ch
		label	L846_str__hla_ byte
		db	"sumIsPositive returned true!"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L864_len__hla_ word
		dd	011h
		dd	011h
		label	L864_str__hla_ byte
		db	"Provide a value: "
		db	0

		db	0
		db	0
