
		align	4
		label	L825_len__hla_ word
		dd	015h
		dd	015h
		label	L825_str__hla_ byte
		db	"Gimme a goal number: "
		db	0

		db	0
		db	0

		align	4
		label	L840_len__hla_ word
		dd	09h
		dd	09h
		label	L840_str__hla_ byte
		db	"Feed Me: "
		db	0

		db	0
		db	0

		align	4
		label	L857_len__hla_ word
		dd	012h
		dd	012h
		label	L857_str__hla_ byte
		db	"You Hit The Match!"
		db	0

		db	0

		align	4
		label	L875_len__hla_ word
		dd	0ch
		dd	0ch
		label	L875_str__hla_ byte
		db	"You Fed Me: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L889_len__hla_ word
		dd	019h
		dd	019h
		label	L889_str__hla_ byte
		db	" positive quantities and "
		db	0

		db	0
		db	0

		align	4
		label	L903_len__hla_ word
		dd	014h
		dd	014h
		label	L903_str__hla_ byte
		db	" negative quantities"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L921_len__hla_ word
		dd	027h
		dd	027h
		label	L921_str__hla_ byte
		db	"Longest Positive Streak Of Quantities: "
		db	0


		align	4
		label	L935_len__hla_ word
		dd	027h
		dd	027h
		label	L935_str__hla_ byte
		db	"Longest Negative Streak Of Quantities: "
		db	0

