
		align	4
		label	L822_len__hla_ word
		dd	0ah
		dd	0ah
		label	L822_str__hla_ byte
		db	"Here is A="
		db	0

		db	0

		align	4
		label	L836_len__hla_ word
		dd	0bh
		dd	0bh
		label	L836_str__hla_ byte
		db	" Here is a="
		db	0


		align	4
		label	L850_len__hla_ word
		dd	022h
		dd	022h
		label	L850_str__hla_ byte
		db	"Gimme a character, any character: "
		db	0

		db	0

		align	4
		label	L864_len__hla_ word
		dd	017h
		dd	017h
		label	L864_str__hla_ byte
		db	"Here's your character: "
		db	0

