
		align	4
		label	L831_len__hla_ word
		dd	02h
		dd	02h
		label	L831_str__hla_ byte
		db	"A["
		db	0

		db	0

		align	4
		label	L845_len__hla_ word
		dd	02h
		dd	02h
		label	L845_str__hla_ byte
		db	"]="
		db	0

		db	0

		align	4
		label	L860_len__hla_ word
		dd	01dh
		dd	01dh
		label	L860_str__hla_ byte
		db	"Gimme a size for your array: "
		db	0

		db	0
		db	0

		align	4
		label	L888_len__hla_ word
		dd	019h
		dd	019h
		label	L888_str__hla_ byte
		db	"Here's the array contents"
		db	0

		db	0
		db	0
