
		align	4
		label	L825_len__hla_ word
		dd	018h
		dd	018h
		label	L825_str__hla_ byte
		db	"Feed me (2 hex digits): "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L863_len__hla_ word
		dd	05h
		dd	05h
		label	L863_str__hla_ byte
		db	" bags"
		db	0

		db	0
		db	0

		align	4
		label	L886_len__hla_ word
		dd	07h
		dd	07h
		label	L886_str__hla_ byte
		db	"No bags"
		db	0


		align	4
		label	L910_len__hla_ word
		dd	04h
		dd	04h
		label	L910_str__hla_ byte
		db	" bag"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L929_len__hla_ word
		dd	0eh
		dd	0eh
		label	L929_str__hla_ byte
		db	"Meal purchased"
		db	0

		db	0

		align	4
		label	L948_len__hla_ word
		dd	07h
		dd	07h
		label	L948_str__hla_ byte
		db	"No meal"
		db	0


		align	4
		label	L967_len__hla_ word
		dd	012h
		dd	012h
		label	L967_str__hla_ byte
		db	"First class ticket"
		db	0

		db	0

		align	4
		label	L986_len__hla_ word
		dd	0eh
		dd	0eh
		label	L986_str__hla_ byte
		db	"Economy ticket"
		db	0

		db	0

		align	4
		label	L1010_len__hla_ word
		dd	0eh
		dd	0eh
		label	L1010_str__hla_ byte
		db	"00 miles flown"
		db	0

		db	0

		align	4
		label	L1028_len__hla_ word
		dd	0eh
		dd	0eh
		label	L1028_str__hla_ byte
		db	"Total Fees = $"
		db	0

		db	0

		align	4
		label	L1053_len__hla_ word
		dd	01bh
		dd	01bh
		label	L1053_str__hla_ byte
		db	"Miles flown cannot be zero!"
		db	0

