
		align	4
		label	L830_len__hla_ word
		dd	013h
		dd	013h
		label	L830_str__hla_ byte
		db	"gimme three values!"
		db	0


		align	4
		label	L871_len__hla_ word
		dd	01ch
		dd	01ch
		label	L871_str__hla_ byte
		db	"after makeThirtyIfOneIsZero!"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L885_len__hla_ word
		dd	016h
		dd	016h
		label	L885_str__hla_ byte
		db	"the first parameter = "
		db	0

		db	0

		align	4
		label	L914_len__hla_ word
		dd	018h
		dd	018h
		label	L914_str__hla_ byte
		db	" the second parameter = "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L943_len__hla_ word
		dd	017h
		dd	017h
		label	L943_str__hla_ byte
		db	" the third parameter = "
		db	0

