
		align	4
		label	L831_len__hla_ word
		dd	0bh
		dd	0bh
		label	L831_str__hla_ byte
		db	"Feed Me X: "
		db	0


		align	4
		label	L853_len__hla_ word
		dd	0bh
		dd	0bh
		label	L853_str__hla_ byte
		db	"Feed Me Y: "
		db	0


		align	4
		label	L875_len__hla_ word
		dd	0bh
		dd	0bh
		label	L875_str__hla_ byte
		db	"Feed Me Z: "
		db	0


		align	4
		label	L897_len__hla_ word
		dd	05h
		dd	05h
		label	L897_str__hla_ byte
		db	"AX = "
		db	0

		db	0
		db	0
