		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L955_str__hla_  equ	L926_str__hla_	;
L950_str__hla_  equ	L829_str__hla_	;
L945_str__hla_  equ	L829_str__hla_	;
L940_str__hla_  equ	L824_str__hla_	;
L935_str__hla_  equ	L906_str__hla_	;
L921_str__hla_  equ	L916_str__hla_	;
L911_str__hla_  equ	L853_str__hla_	;
L892_str__hla_  equ	L887_str__hla_	;
L882_str__hla_  equ	L853_str__hla_	;
L877_str__hla_  equ	L819_str__hla_	;
L863_str__hla_  equ	L858_str__hla_	;
L834_str__hla_  equ	L829_str__hla_	;
