
		align	4
		label	L819_len__hla_ word
		dd	07h
		dd	07h
		label	L819_str__hla_ byte
		db	"PPPP   "
		db	0


		align	4
		label	L824_len__hla_ word
		dd	07h
		dd	07h
		label	L824_str__hla_ byte
		db	"IIIII  "
		db	0


		align	4
		label	L829_len__hla_ word
		dd	07h
		dd	07h
		label	L829_str__hla_ byte
		db	"ZZZZZ  "
		db	0


		align	4
		label	L839_len__hla_ word
		dd	07h
		dd	07h
		label	L839_str__hla_ byte
		db	"  A    "
		db	0


		align	4
		label	L848_len__hla_ word
		dd	07h
		dd	07h
		label	L848_str__hla_ byte
		db	"P   P  "
		db	0


		align	4
		label	L853_len__hla_ word
		dd	07h
		dd	07h
		label	L853_str__hla_ byte
		db	"  I    "
		db	0


		align	4
		label	L858_len__hla_ word
		dd	07h
		dd	07h
		label	L858_str__hla_ byte
		db	"   Z   "
		db	0


		align	4
		label	L868_len__hla_ word
		dd	07h
		dd	07h
		label	L868_str__hla_ byte
		db	" A A   "
		db	0


		align	4
		label	L887_len__hla_ word
		dd	07h
		dd	07h
		label	L887_str__hla_ byte
		db	"  Z    "
		db	0


		align	4
		label	L897_len__hla_ word
		dd	07h
		dd	07h
		label	L897_str__hla_ byte
		db	"AAAAA  "
		db	0


		align	4
		label	L906_len__hla_ word
		dd	07h
		dd	07h
		label	L906_str__hla_ byte
		db	"P      "
		db	0


		align	4
		label	L916_len__hla_ word
		dd	07h
		dd	07h
		label	L916_str__hla_ byte
		db	" Z     "
		db	0


		align	4
		label	L926_len__hla_ word
		dd	07h
		dd	07h
		label	L926_str__hla_ byte
		db	"A   A  "
		db	0

