		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_PUTI32
		global	STDOUT_PUTI32SIZE
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	STDIN_GETI32
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1145_str__hla_ equ	L860_str__hla_	;
L1134_str__hla_ equ	L860_str__hla_	;
L1123_str__hla_ equ	L860_str__hla_	;
L1112_str__hla_ equ	L860_str__hla_	;
L1082_str__hla_ equ	L860_str__hla_	;
L1071_str__hla_ equ	L860_str__hla_	;
L1060_str__hla_ equ	L860_str__hla_	;
L1049_str__hla_ equ	L860_str__hla_	;
L1019_str__hla_ equ	L860_str__hla_	;
L1008_str__hla_ equ	L860_str__hla_	;
L997_str__hla_  equ	L860_str__hla_	;
L986_str__hla_  equ	L860_str__hla_	;
L956_str__hla_  equ	L860_str__hla_	;
L945_str__hla_  equ	L860_str__hla_	;
L934_str__hla_  equ	L860_str__hla_	;
L923_str__hla_  equ	L860_str__hla_	;
L893_str__hla_  equ	L860_str__hla_	;
L882_str__hla_  equ	L860_str__hla_	;
L871_str__hla_  equ	L860_str__hla_	;
