		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	STDOUT_PUTD
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L806_lbl1__hla_ equ	L810_lbl1__hla_
L808_lbl2__hla_ equ	L811_lbl2__hla_
L916_str__hla_  equ	L854_str__hla_	;
L896_str__hla_  equ	L843_str__hla_	;
