
		align	4
		label	L825_len__hla_ word
		dd	019h
		dd	019h
		label	L825_str__hla_ byte
		db	"Using the lea instruction"
		db	0

		db	0
		db	0

		align	4
		label	L843_len__hla_ word
		dd	0bh
		dd	0bh
		label	L843_str__hla_ byte
		db	"--->&lbl1=$"
		db	0


		align	4
		label	L854_len__hla_ word
		dd	07h
		dd	07h
		label	L854_str__hla_ byte
		db	" &lbl2="
		db	0


		align	4
		label	L878_len__hla_ word
		dd	017h
		dd	017h
		label	L878_str__hla_ byte
		db	"Using the & instruction"
		db	0

