
		align	4
		label	L827_len__hla_ word
		dd	018h
		dd	018h
		label	L827_str__hla_ byte
		db	"Feed me (2 hex digits): "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L868_len__hla_ word
		dd	01ch
		dd	01ch
		label	L868_str__hla_ byte
		db	"First part (high nibble): 0x"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L888_len__hla_ word
		dd	01h
		dd	01h
		label	L888_str__hla_ byte
		db	"h"
		db	0

		db	0
		db	0
