
		align	4
		label	L820_len__hla_ word
		dd	018h
		dd	018h
		label	L820_str__hla_ byte
		db	"Gimme a starting value: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L834_len__hla_ word
		dd	012h
		dd	012h
		label	L834_str__hla_ byte
		db	"Rolling Down Table"
		db	0

		db	0

		align	4
		label	L852_len__hla_ word
		dd	02h
		dd	02h
		label	L852_str__hla_ byte
		db	": "
		db	0

		db	0

		align	4
		label	L921_len__hla_ word
		dd	01h
		dd	01h
		label	L921_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0

		align	4
		label	L996_len__hla_ word
		dd	02h
		dd	02h
		label	L996_str__hla_ byte
		db	"  "
		db	0

		db	0
