		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDIN_GETI8
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	STDOUT_PUTI8
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1158_str__hla_ equ	L996_str__hla_	;
L1138_str__hla_ equ	L921_str__hla_	;
L1124_str__hla_ equ	L921_str__hla_	;
L1097_str__hla_ equ	L921_str__hla_	;
L1083_str__hla_ equ	L921_str__hla_	;
L1069_str__hla_ equ	L921_str__hla_	;
L1036_str__hla_ equ	L996_str__hla_	;
L1016_str__hla_ equ	L996_str__hla_	;
L963_str__hla_  equ	L921_str__hla_	;
L949_str__hla_  equ	L921_str__hla_	;
L935_str__hla_  equ	L921_str__hla_	;
L894_str__hla_  equ	L852_str__hla_	;
L880_str__hla_  equ	L852_str__hla_	;
L866_str__hla_  equ	L852_str__hla_	;
