
		align	4
		label	L829_len__hla_ word
		dd	01bh
		dd	01bh
		label	L829_str__hla_ byte
		db	"Surface Area of a sphere = "
		db	0


		align	4
		label	L843_len__hla_ word
		dd	019h
		dd	019h
		label	L843_str__hla_ byte
		db	"Surface Area of a cube = "
		db	0

		db	0
		db	0

		align	4
		label	L857_len__hla_ word
		dd	01dh
		dd	01dh
		label	L857_str__hla_ byte
		db	"Surface Area of a cylinder = "
		db	0

		db	0
		db	0

		align	4
		label	L871_len__hla_ word
		dd	03dh
		dd	03dh
		label	L871_str__hla_ byte
		db	"Lemme calculate the surface area of various things in inches!"
		db	0

		db	0
		db	0

		align	4
		label	L889_len__hla_ word
		dd	09h
		dd	09h
		label	L889_str__hla_ byte
		db	"Gimme r: "
		db	0

		db	0
		db	0

		align	4
		label	L911_len__hla_ word
		dd	09h
		dd	09h
		label	L911_str__hla_ byte
		db	"Gimme h: "
		db	0

		db	0
		db	0
