
		align	4
		label	L828_len__hla_ word
		dd	027h
		dd	027h
		label	L828_str__hla_ byte
		db	"The distance between points A and B is "
		db	0


		align	4
		label	L842_len__hla_ word
		dd	016h
		dd	016h
		label	L842_str__hla_ byte
		db	"Gimme a value for x1: "
		db	0

		db	0

		align	4
		label	L864_len__hla_ word
		dd	016h
		dd	016h
		label	L864_str__hla_ byte
		db	"Gimme a value for x2: "
		db	0

		db	0

		align	4
		label	L886_len__hla_ word
		dd	016h
		dd	016h
		label	L886_str__hla_ byte
		db	"Gimme a value for y1: "
		db	0

		db	0

		align	4
		label	L908_len__hla_ word
		dd	016h
		dd	016h
		label	L908_str__hla_ byte
		db	"Gimme a value for y2: "
		db	0

		db	0
