
		align	4
		label	L833_len__hla_ word
		dd	09h
		dd	09h
		label	L833_str__hla_ byte
		db	"Gimme X: "
		db	0

		db	0
		db	0

		align	4
		label	L855_len__hla_ word
		dd	09h
		dd	09h
		label	L855_str__hla_ byte
		db	"Gimme Y: "
		db	0

		db	0
		db	0

		align	4
		label	L877_len__hla_ word
		dd	09h
		dd	09h
		label	L877_str__hla_ byte
		db	"Gimme Z: "
		db	0

		db	0
		db	0

		align	4
		label	L902_len__hla_ word
		dd	010h
		dd	010h
		label	L902_str__hla_ byte
		db	"After smallest, "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L916_len__hla_ word
		dd	04h
		dd	04h
		label	L916_str__hla_ byte
		db	"X = "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L945_len__hla_ word
		dd	06h
		dd	06h
		label	L945_str__hla_ byte
		db	", Y = "
		db	0

		db	0

		align	4
		label	L974_len__hla_ word
		dd	06h
		dd	06h
		label	L974_str__hla_ byte
		db	", Z = "
		db	0

		db	0
