
		align	4
		label	L833_len__hla_ word
		dd	0fh
		dd	0fh
		label	L833_str__hla_ byte
		db	"gimme a value: "
		db	0


		align	4
		label	L855_len__hla_ word
		dd	015h
		dd	015h
		label	L855_str__hla_ byte
		db	"gimme another value: "
		db	0

		db	0
		db	0

		align	4
		label	L877_len__hla_ word
		dd	015h
		dd	015h
		label	L877_str__hla_ byte
		db	"gimme a final value: "
		db	0

		db	0
		db	0

		align	4
		label	L899_len__hla_ word
		dd	014h
		dd	014h
		label	L899_str__hla_ byte
		db	"Calling Min Function"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L917_len__hla_ word
		dd	01ah
		dd	01ah
		label	L917_str__hla_ byte
		db	"Returned from Min Function"
		db	0

		db	0

		align	4
		label	L935_len__hla_ word
		dd	06h
		dd	06h
		label	L935_str__hla_ byte
		db	"min = "
		db	0

		db	0
