
		align	4
		label	L821_len__hla_ word
		dd	0ah
		dd	0ah
		label	L821_str__hla_ byte
		db	"Feed Me X:"
		db	0

		db	0

		align	4
		label	L843_len__hla_ word
		dd	0ah
		dd	0ah
		label	L843_str__hla_ byte
		db	"Feed Me Y:"
		db	0

		db	0

		align	4
		label	L867_len__hla_ word
		dd	0ah
		dd	0ah
		label	L867_str__hla_ byte
		db	"yes y < x!"
		db	0

		db	0

		align	4
		label	L886_len__hla_ word
		dd	09h
		dd	09h
		label	L886_str__hla_ byte
		db	"no, y < x"
		db	0

		db	0
		db	0
